In [5]:
import numpy as np
import numpy.random as npr

In [24]:
class Parameters:
    def __init__(self):
        self.comp_attribute_sd = 0.2
        self.env_size = 10
        self.open_source = npr.choice([True, False])
        
        

In [7]:
class Computers:
    def __init__(self, params):
        self.env_size = params.env_size
        self.secs = npr.uniform(size=params.env_size)
        self.attns = self.secs + npr.normal(scale=params.comp_attribute_sd, size=params.env_size)
        self.perfs = self.secs + npr.normal(scale=params.comp_attribute_sd, size=params.env_size)
        np.clip(self.attns, 0, 1, self.attns)
        np.clip(self.perfs, 0, 1, self.perfs)
        self.occupants = np.zeros(params.env_size)
        
    def add_ai(self, ai, pos=None):
        if pos is None:
            pos = npr.randint(env_size)
        self.occupants[pos] = AI

In [20]:
class AI:
    def __init__(self, params):
        # These parameters are proportions of time that the agent spends on each task
        proportions = npr.dirichlet(np.ones(5), 1)[0]
        self.exploit, self.self_improv, self.bugfix, self.help_humans, self.work = proportions
    def __repr__(self):
        return "AI(exp:{0:.3f}, imp:{1:.3f}, fix:{2:.3f}, hlp:{3:.3f}, wrk:{4:.3f})".format(
            self.exploit, self.self_improv, self.bugfix, self.help_humans, self.work)
        

In [25]:
class Population:
    def __init__(self, params):
        if params.open_source:
            # sample: [2322, 920, 2544, 440, 1525, 1571, 1464, 303, 1136, 1222, 2032, 391, 2517, 636, 274, 1922, 3540, 3936, 607, 916]
            self.popsize = int(np.ceil(npr.lognormal(npr.uniform(5.0, 8.0))))
        else:
            # sample: [2, 2, 3, 2, 1, 1, 2, 1, 5, 3, 3, 2, 4, 3, 7, 3, 1, 1, 1, 1, 2, 1, 4, 3, 1]
            self.popsize = int(np.ceil(npr.lognormal(0.4)))
        
        self.ais = [AI(params) for n in range(self.popsize)]

In [31]:
params = Parameters()
comps = Computers(params)
AI(params)


In [117]:
x = Population(params)

x.ais

[AI(exp:0.012, imp:0.287, fix:0.085, hlp:0.564, wrk:0.052),
 AI(exp:0.527, imp:0.108, fix:0.099, hlp:0.202, wrk:0.065),
 AI(exp:0.140, imp:0.539, fix:0.011, hlp:0.018, wrk:0.292)]

In [16]:
comps.secs, comps.attns, comps.perfs

(array([ 0.67850837,  0.32367809,  0.18186434,  0.92509432,  0.00949944,
         0.29423108,  0.97183779,  0.76557834,  0.55377642,  0.12289116]),
 array([ 0.67223102,  0.44610274,  0.16835862,  0.78802167,  0.        ,
         0.06413982,  0.95106517,  0.57866962,  0.37615944,  0.        ]),
 array([ 0.66878956,  0.        ,  0.25302042,  0.54906546,  0.06688096,
         0.28872204,  1.        ,  0.60823988,  1.        ,  0.08393622]))